define([
  {
    "projectid": "1",
    "projectname": "黄花机场1#站",
    "industryclassname": "公共建筑",
    "industrytypename": "机场",
    "businesstypename": "BOT",
    "buildingarea": "154000",
    "supplyarea": "120000",
    "pictureptah": "upload/HHJC.jpg",
    "address": "湖南省长沙市长沙县",
    "longitude": 113.23,
    "latitude": 28.2,
    "state": "2"
  },
  {
    "projectid": "3",
    "projectname": "亭湖医院泛能站",
    "industryclassname": "公共建筑",
    "industrytypename": "医院",
    "businesstypename": "EPC",
    "buildingarea": "101308.6",
    "supplyarea": "60785.16",
    "pictureptah": "upload/THYY.jpg",
    "address": "江苏省盐城市亭湖区",
    "longitude": 120.210138,
    "latitude": 33.40249,
    "state": "2"
  },
  {
    "projectid": "4",
    "projectname": "株洲神农城1#站",
    "industryclassname": "公共建筑",
    "industrytypename": "综合",
    "businesstypename": "BOT",
    "buildingarea": "640000",
    "supplyarea": "69000",
    "pictureptah": "upload/shnch.jpg",
    "address": "湖南省株洲市天元区",
    "longitude": 113.082,
    "latitude": 27.827,
    "state": "2"
  },
  {
    "projectid": "6",
    "projectname": "肇庆新区2#能源站",
    "industryclassname": "公共建筑",
    "industrytypename": "学校",
    "businesstypename": "PM",
    "buildingarea": "109188",
    "supplyarea": "69166",
    "pictureptah": "upload/ZQ2.jpg",
    "address": "广东省肇庆市肇庆ZB14区",
    "longitude": 112.45,
    "latitude": 23.033333,
    "state": "2"
  },
  {
    "projectid": "24",
    "projectname": "新奥生态城能源站",
    "industryclassname": "工业企业",
    "industrytypename": "产业园区",
    "businesstypename": null,
    "buildingarea": "0",
    "supplyarea": "0",
    "pictureptah": "upload/ENNSTC.jpg",
    "address": "河北廊坊经济开发区华祥路新源东道",
    "longitude": 116.77712,
    "latitude": 39.558454,
    "state": "2"
  },
  {
    "projectid": "5",
    "projectname": "株洲职教城一阶段能源站",
    "industryclassname": "公共建筑",
    "industrytypename": "学校",
    "businesstypename": "EPC",
    "buildingarea": "279100",
    "supplyarea": "279100",
    "pictureptah": "upload/ZZZJC.jpg",
    "address": "湖南株洲职教城",
    "longitude": 113.084132,
    "latitude": 27.872339,
    "state": "1"
  },
  {
    "projectid": "7",
    "projectname": "洛阳民生药业项目(一期)",
    "industryclassname": "工业企业",
    "industrytypename": "产业园区",
    "businesstypename": "EPC",
    "buildingarea": "2077",
    "supplyarea": "37000",
    "pictureptah": "upload/MSYY.jpg",
    "address": "河南省嵩县田湖镇",
    "longitude": 112.467822,
    "latitude": 34.634309,
    "state": "1"
  },
  {
    "projectid": "8",
    "projectname": "振西商贸广场泛能站",
    "industryclassname": "商业零售",
    "industrytypename": "城市综合体",
    "businesstypename": "EPC",
    "buildingarea": "197800.27",
    "supplyarea": "168604",
    "pictureptah": "upload/empty.jpg",
    "address": "石家庄市槐安西路北侧，城角街西侧",
    "longitude": 114.511359,
    "latitude": 38.043327,
    "state": "1"
  },
  {
    "projectid": "9",
    "projectname": "海宁杭海国际项目",
    "industryclassname": "商业零售",
    "industrytypename": "城市综合体",
    "businesstypename": "EPC",
    "buildingarea": "230000",
    "supplyarea": "230000",
    "pictureptah": "upload/empty.jpg",
    "address": "杭州临平南苑站地铁出站口",
    "longitude": 120.143807,
    "latitude": 30.301459,
    "state": "1"
  },
  {
    "projectid": "10",
    "projectname": "中德1#泛能站 ",
    "industryclassname": "公共建筑",
    "industrytypename": "生态园",
    "businesstypename": "PM",
    "buildingarea": "3632",
    "supplyarea": "590000",
    "pictureptah": "upload/ZD1.jpg",
    "address": "青岛中德生态园",
    "longitude": 120.132596,
    "latitude": 36.068777,
    "state": "1"
  },
  {
    "projectid": "11",
    "projectname": "新朝阳泛能微网示范项目",
    "industryclassname": "商业零售",
    "industrytypename": "城市综合体",
    "businesstypename": "未知",
    "buildingarea": "40000",
    "supplyarea": "1150000",
    "pictureptah": "upload/empty.jpg",
    "address": "廊坊市广阳区",
    "longitude": 116.726024,
    "latitude": 39.534042,
    "state": "1"
  },
  {
    "projectid": "12",
    "projectname": "蚌埠大明产业园",
    "industryclassname": "商业零售",
    "industrytypename": "餐饮店",
    "businesstypename": "EPC",
    "buildingarea": "61887",
    "supplyarea": "49510",
    "pictureptah": "upload/empty.jpg",
    "address": "蚌埠市龙子湖区李楼乡东西芦山",
    "longitude": 117.465204,
    "latitude": 32.898389,
    "state": "0"
  },
  {
    "projectid": "13",
    "projectname": "新安煤清洁高效利用煤气发生站",
    "industryclassname": "工业企业",
    "industrytypename": "产业园区",
    "businesstypename": "未知",
    "buildingarea": null,
    "supplyarea": null,
    "pictureptah": "upload/empty.jpg",
    "address": "洛阳市新安县产业集聚区",
    "longitude": 112.164267,
    "latitude": 34.736893,
    "state": "0"
  },
  {
    "projectid": "14",
    "projectname": "西安华润万象城",
    "industryclassname": "商业零售",
    "industrytypename": "城市综合体",
    "businesstypename": "EPC",
    "buildingarea": "1500000",
    "supplyarea": "1500000",
    "pictureptah": "upload/empty.jpg",
    "address": "西安市未央区三桥",
    "longitude": 108.595191,
    "latitude": 34.337238,
    "state": "0"
  },
  {
    "projectid": "15",
    "projectname": "浏阳热力产业园升级改造",
    "industryclassname": "工业企业",
    "industrytypename": "产业园区",
    "businesstypename": "未知",
    "buildingarea": null,
    "supplyarea": null,
    "pictureptah": "upload/empty.jpg",
    "address": "浏阳市经济技术开发区扬清路15号",
    "longitude": 112.991714,
    "latitude": 28.16489,
    "state": "0"
  },
  {
    "projectid": "16",
    "projectname": "兴隆化工节能改造项目",
    "industryclassname": "工业企业",
    "industrytypename": "化学工业",
    "businesstypename": "未知",
    "buildingarea": "0",
    "supplyarea": "0",
    "pictureptah": "upload/empty.jpg",
    "address": "湖南省株洲市石峰区龙头铺工业小区",
    "longitude": 113.135012,
    "latitude": 27.907076,
    "state": "0"
  },
  {
    "projectid": "17",
    "projectname": "中德4#泛能站",
    "industryclassname": "公共建筑",
    "industrytypename": "生态园",
    "businesstypename": "未知",
    "buildingarea": "2413",
    "supplyarea": "1050000",
    "pictureptah": "upload/ZD1.jpg",
    "address": "青岛中德生态园",
    "longitude": 120.132,
    "latitude": 36.06879,
    "state": "0"
  },
  {
    "projectid": "23",
    "projectname": "南汇智城能源站",
    "industryclassname": "公共建筑",
    "industrytypename": "工业园区",
    "businesstypename": "未知",
    "buildingarea": "320000",
    "supplyarea": "0",
    "pictureptah": "upload/NHZC.jpg",
    "address": "上海市浦东新区沪南路8666弄",
    "longitude": 121.432768,
    "latitude": 31.126318,
    "state": "0"
  },
  {
    "projectid": "25",
    "projectname": "东方伟业商业广场能源站",
    "industryclassname": "商业零售",
    "industrytypename": "城市综合体",
    "businesstypename": "BOT",
    "buildingarea": "93248",
    "supplyarea": "53000",
    "pictureptah": "upload/DFWY.jpg",
    "address": "江苏省镇江市润州区中山北路1号",
    "longitude": 119.42775,
    "latitude": 32.220321,
    "state": "0"
  },
  {
    "projectid": "26",
    "projectname": "中国工程院节能改造项目",
    "industryclassname": "公共建筑",
    "industrytypename": "科研院所",
    "businesstypename": "未知",
    "buildingarea": "22883",
    "supplyarea": "20110",
    "pictureptah": "upload/CHNGCY.jpg",
    "address": "中国工程院位于北京市西城区德外冰窖口胡同2号院 ",
    "longitude": 116.377823,
    "latitude": 39.928215,
    "state": "0"
  }
])